server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/ecommerce-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: 7qH8b8TS5cbkEYtXxjA58ZHMrebsy4LF
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
  cloud:
    gateway:
      default-filters:
        - TokenRelay # <--- SİHİRLİ KOD: Token'ı alıp User-Service'e iletir.  # <--- Login olmuş kullanıcının token'ını arkaya iletir
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
