server:
  port: 8761 # Eureka'nın çalıştığı port

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # "Kendini rehbere kaydetme."
    fetch-registry: false       # "Rehberi kimseden indirme."
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ✅ ZIPKIN AYARLARI EKLENDİ
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
